# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables: 
  buildConfiguration: 'Release'

stages:
- stage: Production
  displayName: Production
  jobs:
  - job: BuildTest
    displayName: Restore and test projects
    pool:
      name: localagent
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK 6.0'
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build userservice'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: 'userservice/userservice.csproj'

    
    - task: DotNetCoreCLI@2
      displayName: 'Build projectservice'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: 'projectservice/projectservice.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build emailconsumer service'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: 'emailappservice/emailappservice.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build document service'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: 'documentbgservice/documentbgservice.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build api gateway'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: 'APIGateway/APIGateway.csproj'
    