# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables: 
  buildConfiguration: 'Release'

stages:
- stage: Production
  displayName: Production
  jobs:
  - job: BuildTest
    displayName: Restore and test projects
    pool:
      name: localagent
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK 6.0'
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build userservice'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/userservice.csproj'

    
    - task: DotNetCoreCLI@2
      displayName: 'Build projectservice'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/projectservice.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build emailconsumer service'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/emailappservice.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build document service'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/documentbgservice.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: 'Build api gateway'
      inputs:
        command: build
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/APIGateway.csproj'
  - job: CreateImage  
    displayName: Build/push docker images
    dependsOn: BuildTest
    pool:
      name: localagent
    steps:
    - task: Docker@2
      displayName: 'Build image and push for userservice:$(tag)'
      inputs:
        containerRegistry: 'copyclouddocker'
        repository: 'userservice'
        command: 'buildAndPush'
        Dockerfile: 'userservice/Dockerfile'
        buildContext: 'userservice'
    - task: Docker@2
      displayName: 'Build image and push for projectservice:$(tag)'
      inputs:
        containerRegistry: 'copyclouddocker'
        repository: 'projectservice'
        command: 'buildAndPush'
        Dockerfile: 'projectservice/Dockerfile'
        buildContext: 'projectservice'
    - task: Docker@2
      displayName: 'Build image and push for documentservice:$(tag)'
      inputs:
        containerRegistry: 'copyclouddocker'
        repository: 'documentbgservice'
        command: 'buildAndPush'
        Dockerfile: 'documentbgservice/Dockerfile'
        buildContext: 'documentbgservice'
    - task: Docker@2
      displayName: 'Build image and push for emailservice:$(tag)'
      inputs:
        containerRegistry: 'copyclouddocker'
        repository: 'emailappservice'
        command: 'buildAndPush'
        Dockerfile: 'emailappservice/Dockerfile'
        buildContext: 'emailappservice'
    - task: Docker@2
      displayName: 'Build image and push for API gateway:$(tag)'
      inputs:
        containerRegistry: 'copyclouddocker'
        repository: 'apigateway'
        command: 'buildAndPush'
        Dockerfile: 'APIGateway/Dockerfile'
        buildContext: 'APIGateway'