version: '3.4'

networks:
    backend:

services:
    userservice:
      container_name: user-service
      image: ${DOCKER_REGISTRY-}userservice
      build:
        context: .\userservice
        secrets:
          - google_creds
      networks:
        - backend
    contentservice:
        container_name: content-service
        image: ${DOCKER_REGISTSTRY-}contentservice
        build:
            context: .\contentservice
        secrets:
            - google_creds
        networks:
            - backend
        #environment:
        #    - GOOGLE_APPLICATION_CREDENTIALS=firebase-config.json
    apigateway:
        container_name: api-gateway
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: APIGateway/Dockerfile
        ports:
            - 8001:80
        networks:
            - backend
secrets: # Securing the configuration files
  google_creds:
    environment: 
       GOOGLE_APPLICATION_CREDENTIALS=firebase-config.json
