FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY userservice.csproj .
RUN dotnet restore "userservice.csproj"
COPY . .
RUN dotnet publish "userservice.csproj" -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as final
WORKDIR /app
COPY --from=build /publish .

ENTRYPOINT ["dotnet", "userservice.dll"]